; FROM unicolored/php-app

[program:nginx]
command=/usr/sbin/nginx -g "daemon off;"
killasgroup=true
stopasgroup=true
autostart=true
autorestart=unexpected
exitcodes=0,2
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:php-fpm]
command=/usr/sbin/php-fpm8.3 --nodaemonize
autostart=true
autorestart=true
; stdout_logfile=/var/log/php-fpm-stdout.log
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
; stderr_logfile=/var/log/php-fpm-stderr.log
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
exitcodes=0

[program:cron]
command=/usr/sbin/cron -f
autostart=true
autorestart=unexpected
exitcodes=0
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

